# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/abid/Desktop/#codes/#Raylib game project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/abid/Desktop/#codes/#Raylib game project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/abid/Desktop/#codes/#Raylib game project/CMakeFiles" "/Users/abid/Desktop/#codes/#Raylib game project//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/abid/Desktop/#codes/#Raylib game project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tmx_example

# Build rule for target.
tmx_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tmx_example
.PHONY : tmx_example

# fast build rule for target.
tmx_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/build
.PHONY : tmx_example/fast

boss.o: boss.c.o
.PHONY : boss.o

# target to build an object file
boss.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/boss.c.o
.PHONY : boss.c.o

boss.i: boss.c.i
.PHONY : boss.i

# target to preprocess a source file
boss.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/boss.c.i
.PHONY : boss.c.i

boss.s: boss.c.s
.PHONY : boss.s

# target to generate assembly for a file
boss.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/boss.c.s
.PHONY : boss.c.s

character.o: character.c.o
.PHONY : character.o

# target to build an object file
character.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/character.c.o
.PHONY : character.c.o

character.i: character.c.i
.PHONY : character.i

# target to preprocess a source file
character.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/character.c.i
.PHONY : character.c.i

character.s: character.c.s
.PHONY : character.s

# target to generate assembly for a file
character.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/character.c.s
.PHONY : character.c.s

game.o: game.c.o
.PHONY : game.o

# target to build an object file
game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/game.c.o
.PHONY : game.c.o

game.i: game.c.i
.PHONY : game.i

# target to preprocess a source file
game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/game.c.i
.PHONY : game.c.i

game.s: game.c.s
.PHONY : game.s

# target to generate assembly for a file
game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/game.c.s
.PHONY : game.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/main.c.s
.PHONY : main.c.s

map_renderer.o: map_renderer.c.o
.PHONY : map_renderer.o

# target to build an object file
map_renderer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/map_renderer.c.o
.PHONY : map_renderer.c.o

map_renderer.i: map_renderer.c.i
.PHONY : map_renderer.i

# target to preprocess a source file
map_renderer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/map_renderer.c.i
.PHONY : map_renderer.c.i

map_renderer.s: map_renderer.c.s
.PHONY : map_renderer.s

# target to generate assembly for a file
map_renderer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/map_renderer.c.s
.PHONY : map_renderer.c.s

projectile.o: projectile.c.o
.PHONY : projectile.o

# target to build an object file
projectile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/projectile.c.o
.PHONY : projectile.c.o

projectile.i: projectile.c.i
.PHONY : projectile.i

# target to preprocess a source file
projectile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/projectile.c.i
.PHONY : projectile.c.i

projectile.s: projectile.c.s
.PHONY : projectile.s

# target to generate assembly for a file
projectile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmx_example.dir/build.make CMakeFiles/tmx_example.dir/projectile.c.s
.PHONY : projectile.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tmx_example"
	@echo "... boss.o"
	@echo "... boss.i"
	@echo "... boss.s"
	@echo "... character.o"
	@echo "... character.i"
	@echo "... character.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map_renderer.o"
	@echo "... map_renderer.i"
	@echo "... map_renderer.s"
	@echo "... projectile.o"
	@echo "... projectile.i"
	@echo "... projectile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

